### ISSUE TITLE
Hello sir need help? how to open bootstrap modal when reaching specific pdf page?

### ISSUE THREAD

**Issue by saawan787** [loicminghetti/touchpdf#1]

**Comment by loicminghetti** [comment]
Hi
You can perform some actions when reaching a specific page by using the "changed" parameter. For example: 

``` javascript
$(function() {
 $("#myPDF").pdf( {
  source: "demo.pdf",
  tabs: [
   {title: "Section 1", page: 2, color: "orange"},
   {title: "Section 2", page: 3, color: "green"},
   {title: "Section 3", page: 5, color: "blue"},
  ],
  changed: function () {
   if ( $("#myPDF").pdf("getPageNumber") == 5) {
    // do something when page 5 is reached
    alert ("You have reached section 3");
   }
  }
 } );
});
```

Is it what you need?

Loic

**Comment by saawan787** [comment]
Thank you so much!! Its works for me.
but i have one another problem using Next and Previous button click bootstrap modal will be appear that's fine.but instead of that we can do same event in the PDF scrolling.
means at the time page loading all pages of pdf is load and scroll will appear in the right side.by scrolling i am going to second page that time bootstrap modal will be appear automatically.
hope you understand the scenario.if this possible please asap me solution for that.

Thanks in advance!!

**Comment by loicminghetti** [comment]
Hi!
If I understand correctly, you want the user to be able to scroll to the next page, right? eventually showing your modal at a specific page.
Unfortunately scrolling is not possible with TouchPDF. It was designed with touch devices in mind, where swapping makes more sens than scrolling.
Let me know if I didn't get it.
Loic

**Comment by saawan787** [comment]
Thanks for your reply.
