### ISSUE TITLE
zoom shelled?

### ISSUE THREAD

**Issue by MichaelBosello** [loicminghetti/touchpdf#2]
why zoom shell the text? also in the demo

**Comment by loicminghetti** [comment]
Hi, I'm sorry i don't understand the issue, could you please give me more
details? thanks

**Comment by MichaelBosello** [comment]
thanks you for reply, 
the first one is pdf with touchpdf, the second one is with adobe reader
![senzanome](https://cloud.githubusercontent.com/assets/14661511/10232529/964f8912-6889-11e5-8e76-06b80c0142e7.png)
![senzanome 2](https://cloud.githubusercontent.com/assets/14661511/10232536/9c3d50ac-6889-11e5-8e16-d5ae78ea52d6.png)

**Comment by loicminghetti** [comment]
You are right, there is something wrong with the quality of pdf pages being loaded. I will fix this soon. Meanwhile, you can try to adjust the pdfScale option, let me know if it can works for you.

```
$(function() {
  $("#myPDF").pdf( { source: "yourfile.pdf", pdfScale : 2 } );
});
```

**Comment by sannedubois** [comment]
I would like to use touchpdf for my company, but MichaelBosello is right, the pdf's are not really sharp. Is it possible to fix this problem?

**Comment by loicminghetti** [comment]
Hi, thanks for the reminder, v0.4 now fixes the pdf quality issue when zooming
