### ISSUE TITLE
pdf not sharp

### ISSUE THREAD

**Issue by sannedubois** [loicminghetti/touchpdf#3]
I would like to use touchpdf for my company, but MichaelBosello is right, the pdf's are not really sharp. Is it possible to fix this problem?

**Comment by loicminghetti** [comment]
Hi, v0.4 fixes the pdf not sharp issue, let me know if that works for you

**Comment by sannedubois** [comment]
Thanks, it's working. Great!

**Comment by loicminghetti** [comment]
Glad to hear it, and you’re welcome!
