### ISSUE TITLE
TouchPDf

### ISSUE THREAD

**Issue by LakshmiRajitha** [loicminghetti/touchpdf#6]
Hi,

After a lot of search, i found this plugin which meets my need.Sooo many thanks for that. But i am facing difficult to move to the next page when the pdf is zoomed. 

My query is: I am using this plugin for IPAD and when i zoomed the pdf's page and trying to swipe it to the next page but not happening. so please help me how to achieve this.

I want to move to the next page by swiping when the page is already zoomed. 

Please help asap. very urgent requirement.

Thanks in advance,.

**Comment by loicminghetti** [comment]
Hi
Unfortunately when the PDF is zoomed, you can't use swipe to go to the next page. This would conflict with gesture to move around the zoomed page. Have you considered disabling zoom?

**Comment by LakshmiRajitha** [comment]
Hi,

OK. Thanks for your reply. Is there any chance that we can load the PDF
with scroll instead of loading a single page and swipe it for the next one.
So that even I zoomed it I can scroll to next page. Please reply me as soon
as possible. It's a bit urgent requirement for me. I want to enable scroll
and I need zooming functionality as well. So how to give scroll instead of
loading one page and moving to next. Please do reply at earlier.. It wil be
really helpful.

Thanks,
Rajitha CH

**Comment by loicminghetti** [comment]
Hi Rajitha
Sorry, TouchPDF was designed only for swiping pages, as scrolling would not work well with tab buttons. If you only need zooming and scrolling without the tabs, you could try using the original PDF.JS viewer: https://mozilla.github.io/pdf.js/web/viewer.html
Loic

**Comment by LakshmiRajitha** [comment]
Hi Team,

Thanks for the earliest reply. But i have tried the pdf,js as well but it
seems to work with chrome but not working on safari.. how can I fix it.
please help me on this.

Thanks,
Rajitha.CH

**Comment by loicminghetti** [comment]
Hi
TouchPDF is based on pdf.js, so they should both work in the same environment.
May be you're missing compatiblity.js http://stackoverflow.com/questions/17022052/pdf-js-not-working-with-safari
I hope you'll find a solution
Loic

**Comment by LakshmiRajitha** [comment]
Hello Team,

_Regarding TouchPDF:_ One last query from my side, Is *TouchPDF *plugin an
open source ? Could I use it in real time project?

Please do let me know at the earliest. Expecting an earlier reply.

Soo Thanks in Advance.

Regards,
Rajitha CH

**Comment by loicminghetti** [comment]
Yes, check license for restrictions.
https://github.com/loicminghetti/touchpdf/blob/master/LICENSE

Kind regards,
Loic

**Comment by LakshmiRajitha** [comment]
Hi,

How to enable next and previous buttons for Ipad,only swipe is working.
Even Zoom + & - keys also not working. But my concern is i want the next
and previous buttons should work on IPAD.

Please reply at the earliest.

Thank You.

RAJITHA CH

**Comment by LakshmiRajitha** [comment]
Hi,

 i have resolved the button issue. I have a requirement to use this control
but i am not aware whether it supports the things which i am looking for,
please do reply for the same. here is what i really need to know
1. In our project, we are getting pdf's from the server and for that we
   used iframe. now does this plugin supports this without using iframe ?
2. Does this plugin supports taking byte array and display as pdf?

if yes pl guide me how to do it.

Need your earlier response and thanks for the support.

Regards,
Rajitha CH

**Comment by LakshmiRajitha** [comment]
Hi Team,

We have memory issue in our application using touch pdf viewer.  How do i
call the clean up / destroy methods to clear worker process. How to resovle
memory issue

As it is an urgent requirement. Please reply us as soon as possible.

Thanks,
Rajitha.CH
