### ISSUE TITLE
I want to use it instead of iframe and wants to show the pdf  which is on server, does it supports byte array?

### ISSUE THREAD

**Issue by LakshmiRajitha** [loicminghetti/touchpdf#8]
Hi,

 i have resolved the button issue. I have a requirement to use this control but i am not aware whether it supports the things which i am looking for, please do reply for the same. here is what i really need to know
1. In our project, we are getting pdf's from the server and for that we used iframe. now does this plugin supports this without using iframe ?
2. Does this plugin supports taking byte array and display as pdf?

if yes pl guide me how to do it.

Need your earlier response and thanks for the support.

**Comment by loicminghetti** [comment]
Hi,
Please check issues #4 and #5 for already discussed limitations.

**Comment by LakshmiRajitha** [comment]
Hi

Double Tap on a page when zoomed in can be reset back? If so please help me
to get it. please provide a snippet. What is the event and how to reset to
original. Please get back to this as soon as possible . Please do reply
soon.

Urgent requirement.

Thanks.

Rajitha CH
